# Site settings
title: TokLabs
email: toklabs@protonmail.com
description: Cyber Security Research and Rabbit Holes
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.toklabs.com"
twitter_username: TokLabs
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/